from __future__ import annotations

import re
from typing import Any

import requests

from app.core.exceptions import MolecularAIError
from app.services.input_service import detect_input_type, normalize_sequence


RCSB_ENTRY_URL = "https://data.rcsb.org/rest/v1/core/entry/{pdb_id}"
RCSB_PDB_URL = "https://files.rcsb.org/download/{pdb_id}.pdb"
RCSB_SEARCH_URL = "https://search.rcsb.org/rcsbsearch/v2/query"
ESMFOLD_URL = "https://api.esmatlas.com/foldSequence/v1/pdb/"
UNIPROT_SEARCH_URL = "https://rest.uniprot.org/uniprotkb/search"
UNIPROT_ENTRY_URL = "https://rest.uniprot.org/uniprotkb/{accession}.json"


def fold_sequence(query: str) -> dict[str, Any]:
    try:
        sequence = normalize_sequence(query)
        response = requests.post(ESMFOLD_URL, data=sequence, timeout=90)
    except requests.ConnectionError:
        raise MolecularAIError(
            "Sequence folding is temporarily unavailable (ESMFold API is offline). "
            "Please search by PDB ID or canonical human protein name instead.",
            status_code=503,
        )
    if not response.ok:
        raise MolecularAIError(
            "No experimental PDB structure was found, and ESMFold could not generate a structure from the supplied input.",
            status_code=502,
        )
    return {
        "name": "Sequence Fold Prediction",
        "query": query,
        "pdb_id": None,
        "source": "esmfold",
        "pdb_data": response.text,
        "metadata": {
            "prediction": "Generated by ESMFold from raw amino acid sequence.",
            "confidence_note": "pLDDT confidence scores are colored in the structure.",
            "color_scheme": "plddt",
            "input_sequence_length": len(sequence),
        },
    }


def fetch_rcsb_metadata(pdb_id: str) -> dict[str, Any]:
    response = requests.get(RCSB_ENTRY_URL.format(pdb_id=pdb_id.upper()), timeout=30)
    if not response.ok:
        raise MolecularAIError(f"Could not fetch metadata for PDB ID {pdb_id}.", status_code=404)
    payload = response.json()
    struct = payload.get("struct", {})
    return {
        "title": struct.get("title"),
        "descriptor": struct.get("pdbx_descriptor"),
        "organism": payload.get("rcsb_entity_source_organism", []),
        "keywords": payload.get("struct_keywords", {}),
        "experimental_method": payload.get("exptl", []),
        "resolution_combined": payload.get("rcsb_entry_info", {}).get("resolution_combined", []),
        "deposition_date": payload.get("rcsb_accession_info", {}).get("deposit_date"),
    }


def fetch_pdb_data(pdb_id: str) -> str:
    response = requests.get(RCSB_PDB_URL.format(pdb_id=pdb_id.upper()), timeout=30)
    if not response.ok:
        raise MolecularAIError(f"Could not download structure for PDB ID {pdb_id}.", status_code=404)
    return response.text


def fetch_rcsb_pdb_ids_for_accession(accession: str) -> list[str]:
    payload = {
        "query": {
            "type": "terminal",
            "service": "text",
            "parameters": {
                "attribute": "rcsb_polymer_entity_container_identifiers.reference_sequence_identifiers.database_accession",
                "operator": "exact_match",
                "value": accession,
            },
        },
        "return_type": "entry",
        "request_options": {
            "results_content_type": ["experimental"],
            "sort": [{"sort_by": "score", "direction": "desc"}],
            "paginate": {"start": 0, "rows": 20},
        },
    }
    response = requests.post(RCSB_SEARCH_URL, json=payload, timeout=30)
    if not response.ok:
        raise MolecularAIError(f"RCSB lookup failed for UniProt accession {accession}.", status_code=502)
    return [item["identifier"] for item in response.json().get("result_set", []) if item.get("identifier")]


def search_uniprot(query: str, field: str, size: int = 1, reviewed_only: bool = True) -> list[dict[str, Any]]:
    reviewed_clause = " AND reviewed:true" if reviewed_only else ""
    response = requests.get(
        UNIPROT_SEARCH_URL,
        params={
            "query": f"{field}:{query} AND organism_id:9606{reviewed_clause}",
            "fields": "accession,id,protein_name,gene_names,organism_name",
            "format": "json",
            "size": size,
        },
        timeout=30,
    )
    if not response.ok:
        raise MolecularAIError("UniProt lookup failed for the supplied protein query.", status_code=502)
    payload = response.json()
    return payload.get("results", [])


def resolve_uniprot_accession(query: str) -> tuple[str, str] | None:
    gene_matches = search_uniprot(query, "gene")
    if gene_matches:
        return gene_matches[0]["primaryAccession"], extract_uniprot_name(gene_matches[0])

    protein_matches = search_uniprot(query, "protein_name")
    if protein_matches:
        return protein_matches[0]["primaryAccession"], extract_uniprot_name(protein_matches[0])

    return None


def extract_uniprot_name(record: dict[str, Any]) -> str:
    description = record.get("proteinDescription", {})
    recommended = description.get("recommendedName", {}).get("fullName", {}).get("value")
    if recommended:
        return recommended

    contains = description.get("contains", [])
    if contains:
        contained = contains[0].get("recommendedName", {}).get("fullName", {}).get("value")
        if contained:
            return contained

    return record.get("uniProtkbId") or record.get("primaryAccession") or "Resolved Protein"


def parse_resolution_value(value: str) -> float:
    match = re.search(r"(\d+(?:\.\d+)?)", value)
    if match:
        return float(match.group(1))
    return float("inf")


def fetch_uniprot_pdb_ids(accession: str) -> list[dict[str, Any]]:
    response = requests.get(UNIPROT_ENTRY_URL.format(accession=accession), timeout=30)
    if not response.ok:
        raise MolecularAIError(f"UniProt record lookup failed for accession {accession}.", status_code=502)

    payload = response.json()
    cross_references = payload.get("uniProtKBCrossReferences", [])
    pdb_entries = []
    for item in cross_references:
        if item.get("database") != "PDB" or not item.get("id"):
            continue
        properties = {prop.get("key"): prop.get("value") for prop in item.get("properties", [])}
        pdb_entries.append(
            {
                "pdb_id": item["id"],
                "method": properties.get("Method", ""),
                "resolution": parse_resolution_value(properties.get("Resolution", "")),
            }
        )

    unique_entries: dict[str, dict[str, Any]] = {}
    for entry in pdb_entries:
        pdb_id = entry["pdb_id"]
        current = unique_entries.get(pdb_id)
        if current is None or entry["resolution"] < current["resolution"]:
            unique_entries[pdb_id] = entry
    return list(unique_entries.values())


def best_pdb_for_accession(accession: str) -> str | None:
    try:
        rcsb_ids = fetch_rcsb_pdb_ids_for_accession(accession)
    except MolecularAIError:
        rcsb_ids = []

    if rcsb_ids:
        ranked_entries: list[dict[str, Any]] = []
        for pdb_id in rcsb_ids:
            try:
                metadata = fetch_rcsb_metadata(pdb_id)
            except MolecularAIError:
                continue
            resolutions = metadata.get("resolution_combined") or []
            resolution = min(
                (float(value) for value in resolutions if isinstance(value, (int, float))),
                default=float("inf"),
            )
            methods = metadata.get("experimental_method") or []
            method = (methods[0].get("method") if methods else "") or ""
            ranked_entries.append(
                {
                    "pdb_id": pdb_id,
                    "resolution": resolution,
                    "method_rank": 0 if "x-ray" in method.lower() else 1,
                }
            )

        ranked_entries.sort(key=lambda entry: (entry["method_rank"], entry["resolution"], entry["pdb_id"]))
        if ranked_entries:
            return ranked_entries[0]["pdb_id"]

    try:
        uniprot_entries = fetch_uniprot_pdb_ids(accession)
    except MolecularAIError:
        return None

    ranked_entries = sorted(
        uniprot_entries,
        key=lambda entry: (entry["resolution"], entry["pdb_id"]),
    )
    return ranked_entries[0]["pdb_id"] if ranked_entries else None


def search_uniprot_candidates(query: str, limit: int = 8) -> list[dict[str, Any]]:
    response = requests.get(
        UNIPROT_SEARCH_URL,
        params={
            "query": f"({query}) AND organism_id:9606",
            "fields": "accession,id,protein_name,gene_names,organism_name,reviewed",
            "format": "json",
            "size": limit * 3,
        },
        timeout=30,
    )
    if not response.ok:
        raise MolecularAIError("UniProt suggestion lookup failed for the supplied query.", status_code=502)

    results = response.json().get("results", [])
    normalized_query = query.strip().lower()

    def sort_key(record: dict[str, Any]) -> tuple[int, int, int, str]:
        entry_type = record.get("entryType", "")
        reviewed_rank = 0 if "reviewed" in entry_type.lower() else 1
        gene_names = [
            (gene.get("geneName") or {}).get("value", "")
            for gene in (record.get("genes") or [])
            if (gene.get("geneName") or {}).get("value")
        ]
        protein_name = extract_uniprot_name(record)
        exact_rank = 0 if protein_name.lower() == normalized_query or normalized_query in {name.lower() for name in gene_names} else 1
        prefix_rank = 0 if protein_name.lower().startswith(normalized_query) or any(name.lower().startswith(normalized_query) for name in gene_names) else 1
        return (reviewed_rank, exact_rank, prefix_rank, protein_name.lower())

    return sorted(results, key=sort_key)[:limit]


def build_suggestion_result(record: dict[str, Any]) -> dict[str, Any]:
    accession = record["primaryAccession"]
    genes = record.get("genes") or []
    gene_name = ((genes[0].get("geneName") or {}).get("value")) if genes else None
    pdb_id = best_pdb_for_accession(accession)
    return {
        "gene_name": gene_name,
        "protein_name": extract_uniprot_name(record),
        "uniprot_id": accession,
        "pdb_id": pdb_id,
        "organism": ((record.get("organism") or {}).get("scientificName")) or "Homo sapiens",
    }


def resolve_structure(query: str) -> dict[str, Any]:
    normalized = query.strip()
    input_type = detect_input_type(normalized)

    if input_type == "PROTEIN_SEQUENCE":
        return fold_sequence(query)

    if input_type == "SMILES":
        raise MolecularAIError(
            "SMILES inputs must be sent to /api/generate/smiles instead of /api/structure.",
            status_code=422,
        )

    if input_type == "PDB_ID":
        pdb_id = normalized.upper()
        metadata = fetch_rcsb_metadata(pdb_id)
        pdb_data = fetch_pdb_data(pdb_id)
        name = metadata.get("descriptor") or metadata.get("title") or pdb_id
        return {
            "name": name,
            "query": query,
            "pdb_id": pdb_id,
            "source": "rcsb",
            "pdb_data": pdb_data,
            "metadata": metadata,
        }

    resolved = resolve_uniprot_accession(normalized)
    if resolved is not None:
        accession, protein_name = resolved
        print(f"[LOOKUP] Resolved '{normalized}' -> UniProt {accession}")
        pdb_id = best_pdb_for_accession(accession)
        if pdb_id is not None:
            print(f"[LOOKUP] Resolved UniProt {accession} -> PDB {pdb_id}")
            metadata = fetch_rcsb_metadata(pdb_id)
            pdb_data = fetch_pdb_data(pdb_id)
            metadata["uniprot_accession"] = accession
            metadata["resolved_query"] = protein_name
            return {
                "name": protein_name,
                "query": query,
                "pdb_id": pdb_id,
                "source": "rcsb",
                "pdb_data": pdb_data,
                "metadata": metadata,
            }

    raise MolecularAIError(
        "No canonical human UniProt match with an associated experimental structure was found. Try a human gene symbol, protein name, PDB ID, or raw amino acid sequence.",
        status_code=404,
    )
